#pragma once

enum EnEFK {
	enEffect_TowerDown,
	enEffect_MasicCircle,
	enEffect_Knight_Death,
	enEffect_Knight_Thunder,
	enEffect_Knight_Thunder_Charge,
	enEffect_Knight_Ult_Red,
	enEffect_Knight_Ult_Green,
	enEffect_Knight_Ult_Blue,
	enEffect_Knight_Ult_Yellow,
	enEffect_Knight_Ult_Delete_Blue,
	enEffect_Knight_Ult_Aura,
	enEffect_Knight_Attack,
	/*enEffect_Knight_Atk_Red,
	enEffect_Knight_Atk_Green,
	enEffect_Knight_Atk_Blue,
	enEffect_Knight_Atk_Yellow,*/
	enEffect_Knight_FootSmoke,
	enEffect_Knight_AttackChack,
	enEffect_Knight_Skill,
	enEffect_Knight_SkillGround,
	enEffect_Knight_Death_Num,
	enEffect_Knight_GetPower,
	enEffect_Knight_PowerUP,
	enEffect_Knight_GetHoimi,
	enEffect_Knight_LevelUp,
	enEffect_Knight_LevelDown,
	enEffect_Knight_Death_Blue,
	enEffect_Knight_Death_Red,
	enEffect_Knight_Death_Yellow,
	enEffect_Knight_Death_Green,
	enEffect_Neutral_Enemy_Death,
	enEffect_Neutral_Enemy_head_butt,
	enEffect_Neutral_Enemy_WhiteMagic,
	enEffect_Neutral_Enemy_GreenMagic,
	enEffect_Rabbit_Magic,
	enEffect_Rabbit_kirakira,
	enEffect_Num
};

